# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  ImageName: 'bk/aspdemo:$(Build.BuildId)'

container: mcr.microsoft.com/dotnet/aspnet:5.0

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: printenv
  displayName: 'Review Environment'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 3.1.x
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DockerInstaller@0
  displayName: 'Install Docker Tool'
  inputs:
    dockerVersion: '17.09.0-ce'
    
# - script: |
#     rm -rf .git
#   displayName: 'Delete .git folder'

- task: Docker@0
  displayName: 'Run build Dockerfile'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    action: 'Build an image'
    dockerFile: '**/Dockerfile'
    imageName: '$(ImageName)'
    includeSourceTags: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/bin/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'f1e8e27d-10f1-4d17-9d50-d9f38e3e34c3'
    vstsFeedPackagePublish: 'drop'
    versionOption: 'minor'
    packagePublishDescription: 'First .NET Core'
